config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
  end



#会員側
 scope module: :public do
   root to: 'homes#top'
   get '/about' => 'homes#about'
   get '/search', to: 'searches#search'
   resources :users do
     get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
     patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
     get '/like_posts' => 'posts#like_posts'
   end
   
   
   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end

 end

 
devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
#管理者側
 namespace :admin do
   root 'homes#top'
   resources :users, only: [:index, :destroy]
   resources :posts, only: [:index, :destroy]
   resources :post_comments, only: [:index, :destroy]
 end

end

app/models/post.rb
class Post < ApplicationRecord
   has_one_attached :post_image
   
   belongs_to :user
   has_many :likes, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :post_tag_relations, dependent: :destroy
   has_many :tags, through: :post_tag_relations, dependent: :destroy
   
  
   validates :post_image, presence: true
   validates :title,presence: true
   validates :tag,presence: true
   validates :body,presence: true,length: {maximum: 200}
  
   
  def liked_by?(user)
    if user.present? #userという変数の中身があるか確認するメソッド　
      likes.exists?(user_id: user.id)
    end
  end
  
  def get_post_image
    (post_image.attached?) ? post_image : 'no_image.jpg'
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @posts = Post.page(params[:page]).per(10)
  end
  
  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_posts_path
  end
end

app/views/admin/posts/index.html.erb
<h2>投稿一覧</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">投稿画像</th>
      <th scope="col">タイトル</th>
      <th scope="col">タグ</th>
      <th scope="col">キャプション</th>
      <th scope="col"></th></th>
    </tr>
  </thead>
  <% @posts.each do |post| %>
  <tbody>
    <tr>
      <td><%= image_tag post.get_post_image, style: "width: 70px; height: 70px;" %></td>
      <td><%= post.title %></td>
      <td><%= post.tag %></td>
      <td><%= post.body %></td>
      <td><%= link_to '削除', admin_post_path(post.id), method: :delete, class: "btn btn-danger",data: {confirm: "本当に削除しますか？"}  %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<%= paginate @posts %>