config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
  end



#会員側
 scope module: :public do
   root to: 'homes#top'
   get '/about' => 'homes#about'
   get '/search', to: 'searches#search'
   resources :users do
     get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
     patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
     get '/like_posts' => 'posts#like_posts'
   end
   
   
   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end

 end

 
devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
#管理者側
 namespace :admin do
   root 'homes#top'
   resources :users, only: [:index, :destroy]
   resources :posts, only: [:index, :destroy]
   resources :post_comments, only: [:index, :destroy]
 end

end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  
   def index
    @comments = Comment.page(params[:page]).per(10)
   end
  
   def destroy
    Comment.find(params[:id]).destroy
    flash[:success] = "Comment deleted"
    redirect_to admin_post_comments_path
   end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<h2>コメント一覧</h2>

<table class="table">
  <thead>
    <tr>
  　   <th scope="col">コメント画像</th>
  　   <th scope="col">ハンドルネーム</th>
      <th scope="col">コメント</th>
      <th scope="col"></th></th>
    </tr>
  </thead>
  <% @comments.each do |comment| %>
  <tbody>
    <tr>
      <td><%= image_tag comment.post.get_post_image, style: "width: 70px; height: 70px;" %></td>
      <td><%= comment.user.handlename %></td>
      <td><%= comment.comment %></td>  
      <td><%= link_to '削除', admin_post_comment_path(comment.id), method: :delete, class: "btn btn-danger",data: {confirm: "本当に削除しますか？"}  %></td>
    </tr>
  </tbody>
  <% end %>
</table>
<%= paginate @comments %>