config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
  end



#会員側
 scope module: :public do
   root to: 'homes#top'
   get '/about' => 'homes#about'
   get '/search', to: 'searches#search'
   resources :users do
     get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
     patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
     get '/like_posts' => 'posts#like_posts'
   end
   
   
   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end

 end

 
devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
#管理者側
 namespace :admin do
   root 'homes#top'
   resources :users, only: [:index, :destroy]
   resources :posts, only: [:index, :destroy]
   resources :post_comments, only: [:index, :destroy]
 end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :handlename, presence: true
  validates :introduction, length: { maximum: 50}
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
    
  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@mail.com') do |user|
      user.first_name = "山田"
      user.last_name = "太郎"
      user.first_name_kana = "ヤマダ"
      user.last_name_kana = "タロウ"
      user.handlename = "guest"
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
    end
  end
  
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page]).per(10)
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_users_path
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<h2>会員一覧</h2>


<table class="table">
  <thead>
    <tr>
     
      <th scope="col">名前</th>
      <th scope="col">名前（カナ）</th>
      <th scope="col">ハンドルネーム</th>
      <th scope="col">メールアドレス</th>
      <th scope="col"> 退会ステータス</th>
      <th scope="col"></th>
      
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= user.first_name %><%= user.last_name %></td>
      <td><%= user.first_name_kana %><%= user.last_name_kana %></td>
      <td><%= user.handlename %></td>
      <td><%= user.email %></td>
      <td><%= user.is_deleted %></td>
      <td>
       <% if user.email == 'guest@mail.com'%>
        
       <% else %> 
        <%= link_to '削除', admin_user_path(user.id), method: :delete, class: "btn btn-danger",data: {confirm: "本当に削除しますか？"}  %>
       <% end %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
<%= paginate @users %>