config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
  end



#会員側
 scope module: :public do
   root to: 'homes#top'
   get '/about' => 'homes#about'
   get '/search', to: 'searches#search'
   resources :users do
     get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
     patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
     get '/like_posts' => 'posts#like_posts'
   end
   
   
   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end

 end

 
devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
#管理者側
 namespace :admin do
   root 'homes#top'
   resources :users, only: [:index, :destroy]
   resources :posts, only: [:index, :destroy]
   resources :post_comments, only: [:index, :destroy]
 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
   has_one_attached :post_image
   
   belongs_to :user
   has_many :likes, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :post_tag_relations, dependent: :destroy
   has_many :tags, through: :post_tag_relations, dependent: :destroy
   
  
   validates :post_image, presence: true
   validates :title,presence: true
   validates :tag,presence: true
   validates :body,presence: true,length: {maximum: 200}
  
   
  def liked_by?(user)
    if user.present? #userという変数の中身があるか確認するメソッド　
      likes.exists?(user_id: user.id)
    end
  end
  
  def get_post_image
    (post_image.attached?) ? post_image : 'no_image.jpg'
  end
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :handlename, presence: true
  validates :introduction, length: { maximum: 50}
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
    
  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@mail.com') do |user|
      user.first_name = "山田"
      user.last_name = "太郎"
      user.first_name_kana = "ヤマダ"
      user.last_name_kana = "タロウ"
      user.handlename = "guest"
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
    end
  end
  
  
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  # before_action :authenticate_admin!

def top
   @users = User.page(params[:page]).per(10)
end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @posts = Post.page(params[:page]).per(10)
  end
  
  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_posts_path
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
 #before_action :configure_sign_in_params, only: [:create]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page]).per(10)
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    if resource.class == Admin
      admin_root_path
    else
      user_path(current_user)
    end
    #@handlename = current_user.handlename
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_root_path
    else
      root_path
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name,:last_name,:first_name_kana,:last_name_kana,:handlename])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
</br></br>
<footer class="alert-danger shadow-sm p-1">
  <nav class="navbar navbar-expand-lg navbar-light text-right">
    <div class="mx-auto p-4">
       © 2023 Portforio
    </div>
  </nav>
</footer>

 

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
　
  <li>
    <%= link_to "ホーム",root_path,class: 'nav-link text-light'%>
  </li>
  <li>
    <%=  link_to "マイページ", user_path(current_user.id),class: 'nav-link text-light'%>
  </li>
  <li>
    <%=  link_to "投稿",new_post_path ,class: 'nav-link text-light'  %>
  </li>
  <li>
    <%=  link_to "すべての投稿", posts_path ,class: 'nav-link text-light'  %>
  </li>
  <li>
    <%=  link_to "ユーザー", users_path ,class: 'nav-link text-light'  %>
  </li>
  <li>
    <%= link_to  destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
     <i class="fas fa-sign-out-alt"></i>
    <% end %>
  </li>
  
<% else %>
  
  <li>
    <%= link_to "サイトポリシー", about_path,class: 'nav-link text-light' %>
  </li>
  <li>
    <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
      <i class="fas fa-user-plus"></i> 新規登録
    <% end %>
  </li>
  <li>
    <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
      <i class="fas fa-sign-in-alt"></i> ログイン
    <% end %>
  </li>
  <li>
    <%= link_to users_guest_sign_in_path, method: :post,class: 'nav-link text-light' do %>
     <i class="fas fa-user-alt"></i>ゲスト
    <% end %>
  </li>
<% end %>

app/views/layouts/_header_admin.html.erb
<div class="container mt-4">
  <div class='btn-toolbar' role="toolbar">
    <div class="row justify-content-end">
  <% if admin_signed_in? %>
  <li class="nav-item">
    <%= link_to "ホーム", admin_root_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
  </li>
  <li class="nav-item">
    <%= link_to "会員", admin_users_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
  </li>
  <li class="nav-item">
    <%= link_to "投稿", admin_posts_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
  </li>
  <li class="nav-item">
    <%= link_to "コメント", admin_post_comments_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
  </li>
  <li class="nav-item">
    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary ml-3' %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "ホーム", admin_root_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
  </li>
  <li class="nav-item">
    <%= link_to "ログイン", new_admin_session_path, class: 'btn btn-outline-secondary ml-3' %>
  </li>
<% end %> 
  </div>
 </div>
</div>

app/views/layouts/_header_both.html.erb
 <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        
         <span class="client-name  login-client-name">
          ようこそ、<%= current_user.first_name %>さん！
         </span>
          
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li>
            <%=  link_to user_path(current_user.id),class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to new_post_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> 投稿
            <% end %>
          </li>
          <li>
            <%=  link_to posts_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> すべての投稿
            <% end %>
          </li>
          <li>
            <%#= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
            <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
             <%#<i class="fas fa-sign-out-alt"></i> ログアウト
            <%# end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_admin_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
       <% end %>
        </ul>
  </div>

app/views/layouts/_header_user.html.erb
 <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        
         <span class="client-name  login-client-name">
          ようこそ、<%= current_user.first_name %>さん！
         </span>
          
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li>
            <%=  link_to user_path(current_user.id),class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to new_post_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> 投稿
            <% end %>
          </li>
          <li>
            <%=  link_to posts_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> すべての投稿
            <% end %>
          </li>
          <li>
            <%#= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
            <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
             <%#<i class="fas fa-sign-out-alt"></i> ログアウト
            <%# end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_admin_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
       <% end %>
        </ul>
  </div>

app/views/layouts/_user_errors.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pettonocommunity_Mitene</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5667bc939f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="alert-danger shadow-sm p-1">
      <nav class="navbar navbar-expand-lg navbar-light text-right">
        <div class="container">
          <a class="navbar-brand" href="/"><%= image_tag("logo.jpg",size: "100x100") %></a>
          <a class="navbar-brand" href="/"><span>みんなのペットコミュニティ Mitene</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if params[:controller].include?('admin') %>
                 <%= render 'layouts/header_admin' %>
              <% else %>
                <%= render 'layouts/header' %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
     
    <div class="container">　<%#レスポンシブ対応のクラスになる#%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <% if Rails.env.development? %>
      admin:<%= current_admin.inspect %><br>
      user:<%= current_user.inspect %><br>
      <%= debug params %>
    <% end %>
  </body>
</html>